select COUNTRY_ID from COUNTRIES;

select EMPLOYEE_ID,START_DATE,END_DATE,JOB_ID from JOB_HISTORY;

select distinct FIRST_NAME from  EMPLOYEES;

select FIRST_NAME from EMPLOYEES where FIRST_NAME='David';

select EMPLOYEE_ID from EMPLOYEES where EMPLOYEE_ID = 107;

select EMPLOYEE_ID from JOB_HISTORY where EMPLOYEE_ID>150;

select FIRST_NAME, HIRE_DATE from EMPLOYEES where EMPLOYEE_ID<>111;